source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FIDynamicViewController_Example', :exclusive => true do
  pod "FIDynamicViewControllerNew", :path => "../"
end

target 'FIDynamicViewController_Tests', :exclusive => true do
  pod "FIDynamicViewControllerNew", :path => "../"

  
end
